.\objects\user_mqtt_task.o: user\user_sim7600\user_mqtt_task.c
.\objects\user_mqtt_task.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\user_mqtt_task.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\string.h
.\objects\user_mqtt_task.o: .\uCOS-II\Source\ucos_ii.h
.\objects\user_mqtt_task.o: .\APP\app_cfg.h
.\objects\user_mqtt_task.o: .\APP\os_cfg.h
.\objects\user_mqtt_task.o: .\uCOS-II\Ports\os_cpu.h
.\objects\user_mqtt_task.o: user\user_sim7600\user_mqtt_task.h
.\objects\user_mqtt_task.o: .\user\user_debug.h
.\objects\user_mqtt_task.o: user\user_sim7600\sim7600.h
.\objects\user_mqtt_task.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\user_mqtt_task.o: .\FWlib\inc\stm32f10x_gpio.h
.\objects\user_mqtt_task.o: .\CMSIS\stm32f10x.h
.\objects\user_mqtt_task.o: .\CMSIS\core_cm3.h
.\objects\user_mqtt_task.o: .\CMSIS\system_stm32f10x.h
.\objects\user_mqtt_task.o: .\user\stm32f10x_conf.h
.\objects\user_mqtt_task.o: .\FWlib\inc\stm32f10x_gpio.h
.\objects\user_mqtt_task.o: .\FWlib\inc\stm32f10x_rcc.h
.\objects\user_mqtt_task.o: .\CMSIS\stm32f10x.h
.\objects\user_mqtt_task.o: .\APP\app.h
.\objects\user_mqtt_task.o: .\malloc\malloc.h
